APPLICATION = exp_m3

BOARD ?= iotlab-m3
DEVELHELP ?= 0

USEMODULE += alive
USEMODULE += ztimer_msec

include $(CURDIR)/../../Makefile.exp.include
include $(CURDIR)/../Makefile.exp.include

include $(RIOTBASE)/Makefile.include
