# Configure connection manager params
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MIN=15000
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MAX=35000
CFLAGS += -DNIMBLE_RPBLE_CONN_LATENCY=0
CFLAGS += -DNIMBLE_RPBLE_CONN_SUPER_TO=375000

CFLAGS += -DNIMBLE_AUTOCONN_CONN_ITVL_MS=75
CFLAGS += -DNIMBLE_AUTOCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_AUTOCONN_CONN_SVTO_MS=1500


CFLAGS += -DNIMBLE_STATCONN_CONNITVLRAND=1
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MIN_MS=15
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MAX_MS=35
CFLAGS += -DNIMBLE_STATCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_STATCONN_CONN_SUPERTO_MS=375

CFLAGS += -DCONFIG_GCOAP_NON_TIMEOUT=25000000
