# Configure connection manager params
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MIN=990000
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MAX=1010000
CFLAGS += -DNIMBLE_RPBLE_CONN_LATENCY=0
CFLAGS += -DNIMBLE_RPBLE_CONN_SUPER_TO=15000000

CFLAGS += -DNIMBLE_AUTOCONN_CONN_ITVL_MS=75
CFLAGS += -DNIMBLE_AUTOCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_AUTOCONN_CONN_SVTO_MS=1500


CFLAGS += -DNIMBLE_STATCONN_CONNITVLRAND=1
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MIN_MS=990
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MAX_MS=1010
CFLAGS += -DNIMBLE_STATCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_STATCONN_CONN_SUPERTO_MS=15000

CFLAGS += -DCONFIG_GCOAP_NON_TIMEOUT=25000000
