# Configure connection manager params
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MIN=240000
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MAX=260000
CFLAGS += -DNIMBLE_RPBLE_CONN_LATENCY=0
CFLAGS += -DNIMBLE_RPBLE_CONN_SUPER_TO=3750000

CFLAGS += -DNIMBLE_AUTOCONN_CONN_ITVL_MS=75
CFLAGS += -DNIMBLE_AUTOCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_AUTOCONN_CONN_SVTO_MS=1500


CFLAGS += -DNIMBLE_STATCONN_CONNITVLRAND=1
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MIN_MS=240
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MAX_MS=260
CFLAGS += -DNIMBLE_STATCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_STATCONN_CONN_SUPERTO_MS=3750

CFLAGS += -DCONFIG_GCOAP_NON_TIMEOUT=25000000
