# Configure gcoap
CFLAGS += -DCONFIG_GCOAP_PDU_BUF_SIZE=128
CFLAGS += -DCONFIG_GCOAP_RESEND_BUFS_MAX=40
CFLAGS += -DCONFIG_GCOAP_REQ_WAITING_MAX=40

# Configure NimBLE
CFLAGS += -DNIMBLE_NETIF_MTU=800
