# Configure connection manager params
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MIN=950000
CFLAGS += -DNIMBLE_RPBLE_CONN_ITVL_MAX=1050000
CFLAGS += -DNIMBLE_RPBLE_CONN_LATENCY=0
CFLAGS += -DNIMBLE_RPBLE_CONN_SUPER_TO=10000000

CFLAGS += -DNIMBLE_AUTOCONN_CONN_ITVL_MS=1000
CFLAGS += -DNIMBLE_AUTOCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_AUTOCONN_CONN_SVTO_MS=10000


CFLAGS += -DNIMBLE_STATCONN_CONNITVLRAND=1
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MIN_MS=950
CFLAGS += -DNIMBLE_STATCONN_CONN_ITVL_MAX_MS=1050
CFLAGS += -DNIMBLE_STATCONN_CONN_LATENCY=0
CFLAGS += -DNIMBLE_STATCONN_CONN_SUPERTO_MS=10000

CFLAGS += -DCONFIG_GCOAP_NON_TIMEOUT=20000000
