APPLICATION = exp_statconn

DEVELHELP ?= 1
NIMBLE_MAX_CONN ?= 3

include $(CURDIR)/../../Makefile.exp.include
include $(CURDIR)/../Makefile.exp.include

USEMODULE += nimble_statconn

include $(RIOTBASE)/Makefile.include
